// STUN improves direct cross-city connectivity; no TURN relay is configured.
const rtcConfig = { iceServers: [{ urls: "stun:stun.l.google.com:19302" }] };
const storageKey = "our-private-life-session";
const historyGuardKey = "our-private-life-history-guard";
const verificationEmojis = ["🌙", "⭐", "🪐", "🌊", "🌿", "🔥", "🦋", "🐚", "🪶", "🍀", "🫶", "🎈", "🌈", "🧿", "🔐", "🕯️", "🪞", "🎵", "🧩", "🌻", "☁️", "🐬", "🦊", "🌸", "🍉", "🪁", "🔭", "💫", "🪨", "🧵", "🎐", "🪬"];
let peerConnection, localStream, chatChannel, offerCode = "", answerCode = "";
const $ = (id) => document.getElementById(id);
const elements = {
  setupPage: $("setupPage"), callPage: $("callPage"), localVideo: $("localVideo"), remoteVideo: $("remoteVideo"), start: $("startCameraButton"), createOffer: $("createOfferButton"), createAnswer: $("createAnswerButton"), acceptAnswer: $("acceptAnswerButton"), enterCallAfterAnswer: $("enterCallAfterAnswerButton"), toggleMic: $("toggleMicButton"), toggleCamera: $("toggleCameraButton"), sideBySide: $("sideBySideButton"), switchScreens: $("switchScreensButton"), toggleFullscreen: $("toggleFullscreenButton"), toggleChat: $("toggleChatButton"), closeChat: $("closeChatButton"), chatPanel: $("chatPanel"), chatMessages: $("chatMessages"), chatForm: $("chatForm"), chatInput: $("chatInput"), sendChat: $("sendChatButton"), disconnect: $("disconnectButton"), remoteOffer: $("remoteOffer"), remoteAnswer: $("remoteAnswer"), pasteOffer: $("pasteOfferButton"), pasteAnswer: $("pasteAnswerButton"), copyOffer: $("copyOfferButton"), copyAnswer: $("copyAnswerButton"), copyAnswerInCall: $("copyAnswerInCallButton"), callControls: document.querySelector(".call-controls"), receiverCard: $("receiverCard"), answerReady: $("answerReady"), callerAnswerCard: $("callerAnswerCard"), statusText: $("statusText"), statusDot: $("statusDot"), callStatusText: $("callStatusText"), callStatusDot: $("callStatusDot"), showVerification: $("showVerificationButton"), hideVerification: $("hideVerificationButton"), verificationCard: $("verificationCard"), verificationEmojis: $("verificationEmojis"), verificationCode: $("verificationCode"), videos: $("videos"), localVideoCard: $("localVideoCard"), remoteVideoCard: $("remoteVideoCard")
};
function historyGuardState() { return { ...(history.state || {}), [historyGuardKey]: true }; }
function lockBrowserBackNavigation() { history.replaceState(historyGuardState(), ""); history.pushState(historyGuardState(), ""); }
function blockBrowserBackNavigation() { history.pushState(historyGuardState(), ""); }
function isTextEntry(target) { return target instanceof HTMLElement && target.matches("textarea, input:not([type=button]):not([type=checkbox]):not([type=radio]), [contenteditable=true]"); }
function blockBackShortcuts(event) { if (isTextEntry(event.target)) return; if (event.key === "Backspace" || ((event.altKey || event.metaKey) && event.key === "ArrowLeft")) event.preventDefault(); }
function fingerprintLines(description) { return (description?.sdp?.match(/^a=fingerprint:[^\r\n]+/gmi) || []).map(line => line.trim().toLowerCase().replace(/\s+/g, " ")); }
async function verificationPhrase() { const fingerprints = [...new Set([...fingerprintLines(peerConnection?.localDescription), ...fingerprintLines(peerConnection?.remoteDescription)])].sort(); if (!crypto.subtle || fingerprints.length < 2) throw new Error("Connection fingerprints are not ready yet."); const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(fingerprints.join("\n")))); const code = String(((digest[0] << 16) | (digest[1] << 8) | digest[2]) % 1000000).padStart(6, "0").replace(/(\d{3})(\d{3})/, "$1 $2"); const emojis = Array.from(digest.slice(3, 7), byte => verificationEmojis[byte % verificationEmojis.length]).join(" "); return { code, emojis }; }
function setVerificationVisible(visible) { elements.verificationCard.hidden = !visible; elements.showVerification.setAttribute("aria-expanded", String(visible)); elements.showVerification.setAttribute("aria-label", visible ? "Hide verification code" : "Show verification code"); elements.showVerification.title = visible ? "Hide verification code" : "Show verification code"; elements.showVerification.textContent = visible ? "Hide" : "Verify"; }
async function showVerificationPhrase() { try { const { code, emojis } = await verificationPhrase(); elements.verificationEmojis.textContent = emojis; elements.verificationCode.textContent = code; elements.showVerification.disabled = false; setVerificationVisible(false); } catch (error) { console.warn("Could not create verification phrase.", error); clearVerificationPhrase(); } }
function clearVerificationPhrase() { elements.verificationCard.hidden = true; elements.verificationEmojis.textContent = ""; elements.verificationCode.textContent = ""; elements.showVerification.disabled = true; elements.showVerification.setAttribute("aria-expanded", "false"); elements.showVerification.setAttribute("aria-label", "Show verification code"); elements.showVerification.title = "Show verification code"; elements.showVerification.textContent = "Verify"; }
function saveSession() { sessionStorage.setItem(storageKey, JSON.stringify({ offerCode, answerCode, remoteOffer: elements.remoteOffer.value, remoteAnswer: elements.remoteAnswer.value, sideBySide: elements.videos.classList.contains("side-by-side"), screensSwapped: elements.videos.classList.contains("screens-swapped") })); }
function clearSession() { sessionStorage.removeItem(storageKey); }
function setStatus(message, state = "idle") { [elements.statusText, elements.callStatusText].forEach(node => { node.textContent = message; }); [elements.statusDot, elements.callStatusDot].forEach(node => { node.className = `dot ${state}`; }); }
function showError(error) { console.error(error); setStatus(`Error: ${error.message || error}`, "error"); }
function setBusy(button, busy, label) { button.disabled = busy; if (label) button.textContent = label; }
function base64UrlDecode(code) { const base64 = code.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(code.length / 4) * 4, "="); return Uint8Array.from(atob(base64), character => character.charCodeAt(0)); }
async function gunzip(bytes) { const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip")); return new Uint8Array(await new Response(stream).arrayBuffer()); }
function encodeCode(description) { const bytes = new TextEncoder().encode(JSON.stringify(description)); return btoa(String.fromCharCode(...bytes)); }
async function decodeCode(code, expectedType) { try { const compactCode = code.trim().replace(/\s/g, ""); const bytes = compactCode.startsWith("OPL2.") ? await gunzip(base64UrlDecode(compactCode.slice(5))) : Uint8Array.from(atob(compactCode), character => character.charCodeAt(0)); const value = JSON.parse(new TextDecoder().decode(bytes)); if (value?.type === expectedType && value?.sdp) return value; } catch {} throw new Error(`Paste a valid ${expectedType === "offer" ? "invite" : "response"} code.`); }
function liveTrack(kind) { return localStream?.getTracks().find(track => track.kind === kind && track.readyState === "live"); }
function watchMicrophone(track) { track.addEventListener("ended", () => { if (!localStream?.getAudioTracks().includes(track) || peerConnection?.connectionState === "closed") return; syncMediaControls(); setStatus("Microphone unavailable — select Mic to reconnect", "error"); }); }
function syncMediaControls() { const audio = liveTrack("audio"), video = liveTrack("video"); elements.toggleMic.disabled = !localStream; elements.toggleCamera.disabled = !video; if (audio) { const muted = !audio.enabled; elements.toggleMic.setAttribute("aria-label", muted ? "Unmute microphone" : "Mute microphone"); elements.toggleMic.title = muted ? "Unmute microphone" : "Mute microphone"; elements.toggleMic.setAttribute("aria-pressed", String(muted)); } else if (localStream) { elements.toggleMic.setAttribute("aria-label", "Reconnect microphone"); elements.toggleMic.title = "Reconnect microphone"; elements.toggleMic.setAttribute("aria-pressed", "true"); } if (video) { const off = !video.enabled; elements.toggleCamera.setAttribute("aria-label", off ? "Turn camera on" : "Turn camera off"); elements.toggleCamera.title = off ? "Turn camera on" : "Turn camera off"; elements.toggleCamera.setAttribute("aria-pressed", String(off)); elements.localVideoCard.classList.toggle("camera-disabled", off); } }
async function toggleMicrophone() { const track = liveTrack("audio"); if (track) { track.enabled = !track.enabled; syncMediaControls(); setStatus(track.enabled ? "Microphone turned on" : "Microphone muted", "ready"); return; } if (!localStream) throw new Error("Enable camera and microphone first."); const microphoneStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }), replacementTrack = microphoneStream.getAudioTracks()[0], sender = peerConnection?.getSenders().find(candidate => candidate.track?.kind === "audio"); if (!sender) { replacementTrack.stop(); throw new Error("Microphone cannot be reconnected before the call starts."); } try { await sender.replaceTrack(replacementTrack); localStream.getAudioTracks().forEach(oldTrack => { localStream.removeTrack(oldTrack); oldTrack.stop(); }); localStream.addTrack(replacementTrack); watchMicrophone(replacementTrack); syncMediaControls(); setStatus("Microphone reconnected", "ready"); } catch (error) { replacementTrack.stop(); throw error; } }
async function requestPreferredCameraStream(includeAudio = true) { const profiles = [{ width: 2560, height: 1440 }, { width: 1920, height: 1080 }], retryableErrors = ["OverconstrainedError", "ConstraintNotSatisfiedError", "NotFoundError", "NotReadableError", "AbortError"]; for (const profile of profiles) { try { return await navigator.mediaDevices.getUserMedia({ video: { width: { exact: profile.width }, height: { exact: profile.height }, frameRate: { exact: 30 } }, audio: includeAudio }); } catch (error) { if (!retryableErrors.includes(error.name)) throw error; } } try { return await navigator.mediaDevices.getUserMedia({ video: true, audio: includeAudio }); } catch (error) { if (includeAudio && ["NotReadableError", "AbortError"].includes(error.name)) throw new Error("Microphone is busy or unavailable. End the other call or release its microphone, then try again."); throw error; } }
async function toggleCamera() { const oldTrack = localStream?.getVideoTracks()[0]; if (!oldTrack) throw new Error("Enable camera and microphone first."); if (oldTrack.enabled) { oldTrack.enabled = false; syncMediaControls(); setStatus("Camera turned off", "ready"); return; } const replacementStream = await requestPreferredCameraStream(false); const replacementTrack = replacementStream.getVideoTracks()[0]; const sender = peerConnection?.getSenders().find(candidate => candidate.track?.kind === "video"); try { if (sender) await sender.replaceTrack(replacementTrack); localStream.removeTrack(oldTrack); localStream.addTrack(replacementTrack); oldTrack.stop(); elements.localVideo.srcObject = localStream; syncMediaControls(); setStatus("Camera turned on", "ready"); } catch (error) { replacementTrack.stop(); throw error; } }
function cameraQualityLabel(track) { const { width, height, frameRate } = track.getSettings(); return width && height ? `Camera ready at ${width}×${height}${frameRate ? ` · ${Math.round(frameRate)} fps` : ""}` : "Camera and microphone ready"; }
async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) throw new Error("Camera/microphone access requires HTTPS or localhost."); if (!localStream) { localStream = await requestPreferredCameraStream(); elements.localVideo.srcObject = localStream; localStream.getAudioTracks().forEach(watchMicrophone); } elements.start.textContent = "Camera & microphone enabled"; elements.start.disabled = true; elements.createOffer.disabled = false; syncMediaControls(); setStatus(cameraQualityLabel(localStream.getVideoTracks()[0]), "ready"); }
function makePeerConnection() { if (peerConnection) return peerConnection; if (!localStream) throw new Error("Enable camera and microphone first."); peerConnection = new RTCPeerConnection(rtcConfig); localStream.getTracks().forEach(track => peerConnection.addTrack(track, localStream)); peerConnection.ontrack = ({ streams }) => { elements.remoteVideo.srcObject = streams[0]; }; peerConnection.ondatachannel = ({ channel }) => { if (channel.label === "chat") connectChatChannel(channel); }; peerConnection.onconnectionstatechange = () => { const state = peerConnection.connectionState; setStatus(`Connection: ${state}`, state === "connected" ? "connected" : state === "failed" ? "error" : "working"); }; elements.disconnect.disabled = false; return peerConnection; }
function waitForIceGatheringComplete(pc) { if (pc.iceGatheringState === "complete") return Promise.resolve(); return new Promise(resolve => { const done = () => { if (pc.iceGatheringState === "complete") { pc.removeEventListener("icegatheringstatechange", done); resolve(); } }; pc.addEventListener("icegatheringstatechange", done); }); }
async function copyCode(code, label) { if (!code) throw new Error("Create the code first."); await navigator.clipboard.writeText(code); setStatus(`${label} copied — send it to your friend`, "ready"); }
async function pasteCode(input, label) { try { const code = await navigator.clipboard.readText(); if (!code.trim()) throw new Error("Clipboard is empty."); input.value = code; input.dispatchEvent(new Event("input", { bubbles: true })); input.focus(); setStatus(`${label} pasted from clipboard`, "ready"); } catch (error) { throw new Error(`Could not read the clipboard. Allow clipboard access, then paste the ${label.toLowerCase()} manually.`); } }
function syncResponseCopyControl() { const available = Boolean(answerCode); elements.copyAnswerInCall.hidden = !available; elements.copyAnswerInCall.disabled = !available; elements.callControls.classList.toggle("has-response-copy", available); }
function setChatVisible(visible) { elements.chatPanel.hidden = !visible; elements.chatPanel.setAttribute("aria-hidden", String(!visible)); elements.toggleChat.setAttribute("aria-expanded", String(visible)); elements.toggleChat.setAttribute("aria-label", visible ? "Close chat" : "Open chat"); elements.toggleChat.title = visible ? "Close chat" : "Open chat"; if (visible && !elements.chatInput.disabled) elements.chatInput.focus(); }
function syncChatControls() { const ready = chatChannel?.readyState === "open"; elements.toggleChat.disabled = !ready; elements.chatInput.disabled = !ready; elements.sendChat.disabled = !ready; if (!ready) setChatVisible(false); }
function addChatMessage(message, sender) { const empty = elements.chatMessages.querySelector(".chat-empty"); if (empty) empty.remove(); const item = document.createElement("p"); item.className = `chat-message ${sender}`; item.textContent = message; elements.chatMessages.append(item); elements.chatMessages.scrollTop = elements.chatMessages.scrollHeight; }
function connectChatChannel(channel) { chatChannel = channel; chatChannel.onopen = () => { syncChatControls(); setStatus("Chat ready", "connected"); }; chatChannel.onclose = () => syncChatControls(); chatChannel.onerror = () => { syncChatControls(); setStatus("Chat connection failed", "error"); }; chatChannel.onmessage = (event) => { if (typeof event.data === "string") addChatMessage(event.data.slice(0, 1000), "friend"); }; syncChatControls(); }
function createChatChannel(pc) { connectChatChannel(pc.createDataChannel("chat", { ordered: true })); }
function sendChatMessage(event) { event.preventDefault(); const message = elements.chatInput.value.trim(); if (!message || chatChannel?.readyState !== "open") return; chatChannel.send(message); addChatMessage(message, "self"); elements.chatInput.value = ""; elements.chatInput.focus(); }
function syncFullscreenControl() { const active = document.fullscreenElement === elements.callPage, supported = document.fullscreenEnabled && typeof elements.callPage.requestFullscreen === "function"; elements.toggleFullscreen.disabled = !supported; elements.toggleFullscreen.setAttribute("aria-pressed", String(active)); elements.toggleFullscreen.setAttribute("aria-label", active ? "Exit full screen" : supported ? "Enter full screen" : "Full screen is unavailable in this browser"); elements.toggleFullscreen.title = active ? "Exit full screen" : supported ? "Enter full screen" : "Full screen is unavailable in this browser"; elements.toggleFullscreen.querySelector("span").textContent = active ? "Exit full screen" : "Full screen"; }
async function toggleFullscreen() { try { if (document.fullscreenElement === elements.callPage) await document.exitFullscreen(); else await elements.callPage.requestFullscreen(); } catch (error) { throw new Error("Could not enter full screen. Check your browser permissions and try again.", { cause: error }); } }
function enterCall() { syncResponseCopyControl(); elements.setupPage.hidden = true; elements.callPage.hidden = false; document.title = "Our Private Life — Call"; showVerificationPhrase(); saveSession(); }
async function createOffer() { try { const pc = makePeerConnection(); createChatChannel(pc); setBusy(elements.createOffer, true, "Creating invite…"); await pc.setLocalDescription(await pc.createOffer()); await waitForIceGatheringComplete(pc); offerCode = await encodeCode(pc.localDescription); elements.copyOffer.disabled = false; elements.receiverCard.hidden = true; elements.callerAnswerCard.hidden = false; elements.createOffer.textContent = "Invite created"; saveSession(); setStatus("Invite ready — copy and send it", "ready"); } catch (error) { showError(error); setBusy(elements.createOffer, false, "Create invite"); } }
async function createAnswer() { try { setBusy(elements.createAnswer, true, "Creating response…"); if (!localStream) await startCamera(); const pc = makePeerConnection(); await pc.setRemoteDescription(await decodeCode(elements.remoteOffer.value, "offer")); await pc.setLocalDescription(await pc.createAnswer()); await waitForIceGatheringComplete(pc); answerCode = await encodeCode(pc.localDescription); elements.remoteOffer.hidden = true; elements.createAnswer.hidden = true; elements.answerReady.hidden = false; saveSession(); setStatus("Response ready", "ready"); } catch (error) { showError(error); setBusy(elements.createAnswer, false, "Accept invite & create response"); } }
async function acceptAnswer() { try { if (!peerConnection || !offerCode || peerConnection.signalingState !== "have-local-offer") throw new Error("Invite is no longer active. Create a new invite in this same browser tab; do not reload it."); await peerConnection.setRemoteDescription(await decodeCode(elements.remoteAnswer.value, "answer")); saveSession(); setStatus("Response accepted — connecting…", "working"); enterCall(); } catch (error) { showError(error); } }
function toggleSideBySide() { const active = elements.videos.classList.toggle("side-by-side"); elements.sideBySide.setAttribute("aria-pressed", String(active)); elements.sideBySide.setAttribute("aria-label", active ? "Switch to picture-in-picture view" : "Switch to side-by-side view"); elements.sideBySide.title = active ? "Picture-in-picture view" : "Side-by-side view"; saveSession(); }
function resetTilePosition(card) { card.style.left = ""; card.style.top = ""; card.style.right = ""; card.style.bottom = ""; }
function switchScreens() { resetTilePosition(elements.localVideoCard); resetTilePosition(elements.remoteVideoCard); elements.videos.classList.toggle("screens-swapped"); saveSession(); }
function floatingCard() { return elements.videos.classList.contains("screens-swapped") ? elements.remoteVideoCard : elements.localVideoCard; }
let tileInteraction;
function beginTileDrag(event) { const card = floatingCard(); if (elements.videos.classList.contains("side-by-side") || event.currentTarget !== card || event.target.closest("button")) return; event.preventDefault(); const stage = elements.videos.getBoundingClientRect(), tile = card.getBoundingClientRect(); card.style.left = `${tile.left - stage.left}px`; card.style.top = `${tile.top - stage.top}px`; card.style.right = "auto"; card.style.bottom = "auto"; tileInteraction = { card, stage, offsetX: event.clientX - tile.left, offsetY: event.clientY - tile.top }; document.addEventListener("pointermove", moveTile); document.addEventListener("pointerup", endTileDrag); document.addEventListener("pointercancel", endTileDrag); }
function moveTile(event) { if (!tileInteraction) return; const { card, stage, offsetX, offsetY } = tileInteraction; const left = Math.min(Math.max(event.clientX - stage.left - offsetX, 0), stage.width - card.offsetWidth); const top = Math.min(Math.max(event.clientY - stage.top - offsetY, 0), stage.height - card.offsetHeight); card.style.left = `${left}px`; card.style.top = `${top}px`; }
function endTileDrag() { tileInteraction = undefined; document.removeEventListener("pointermove", moveTile); document.removeEventListener("pointerup", endTileDrag); document.removeEventListener("pointercancel", endTileDrag); }
function releaseLiveResources() { if (peerConnection) peerConnection.close(); if (localStream) localStream.getTracks().forEach(track => track.stop()); }
function disconnect() { if (document.fullscreenElement === elements.callPage) document.exitFullscreen().catch(() => {}); releaseLiveResources(); peerConnection = undefined; localStream = undefined; chatChannel = undefined; offerCode = answerCode = ""; clearVerificationPhrase(); syncResponseCopyControl(); syncChatControls(); elements.chatMessages.replaceChildren(Object.assign(document.createElement("p"), { className: "chat-empty", textContent: "Chat will be ready when your friend connects." })); clearSession(); elements.localVideo.srcObject = null; elements.remoteVideo.srcObject = null; elements.localVideoCard.classList.remove("camera-disabled"); elements.videos.classList.remove("side-by-side", "screens-swapped"); resetTilePosition(elements.localVideoCard); resetTilePosition(elements.remoteVideoCard); elements.sideBySide.setAttribute("aria-pressed", "false"); elements.setupPage.hidden = false; elements.callPage.hidden = true; document.title = "Our Private Life — Direct Call"; elements.start.disabled = false; elements.start.textContent = "Enable camera & microphone"; elements.createOffer.disabled = true; elements.createOffer.textContent = "Create invite"; elements.copyOffer.disabled = true; elements.toggleMic.disabled = true; elements.toggleCamera.disabled = true; elements.disconnect.disabled = true; elements.receiverCard.hidden = false; elements.remoteOffer.hidden = false; elements.remoteOffer.value = ""; elements.createAnswer.hidden = false; elements.createAnswer.disabled = false; elements.createAnswer.textContent = "Accept invite & create response"; elements.answerReady.hidden = true; elements.callerAnswerCard.hidden = true; elements.remoteAnswer.value = ""; syncFullscreenControl(); setStatus("Disconnected", "idle"); }
function restoreSetup() { try { const saved = JSON.parse(sessionStorage.getItem(storageKey) || "null"); if (!saved) return; offerCode = saved.offerCode || ""; answerCode = saved.answerCode || ""; elements.remoteOffer.value = saved.remoteOffer || ""; elements.remoteAnswer.value = saved.remoteAnswer || ""; if (saved.screensSwapped) elements.videos.classList.add("screens-swapped"); if (saved.sideBySide) toggleSideBySide(); if (offerCode) { elements.copyOffer.disabled = false; elements.receiverCard.hidden = true; elements.callerAnswerCard.hidden = false; elements.createOffer.textContent = "Invite created"; } } catch { clearSession(); } }
elements.start.addEventListener("click", () => startCamera().catch(showError)); elements.createOffer.addEventListener("click", createOffer); elements.createAnswer.addEventListener("click", createAnswer); elements.acceptAnswer.addEventListener("click", acceptAnswer); elements.enterCallAfterAnswer.addEventListener("click", enterCall); elements.copyOffer.addEventListener("click", () => copyCode(offerCode, "Invite code").catch(showError)); elements.copyAnswer.addEventListener("click", () => copyCode(answerCode, "Response code").catch(showError)); elements.copyAnswerInCall.addEventListener("click", () => copyCode(answerCode, "Response code").catch(showError)); elements.pasteOffer.addEventListener("click", () => pasteCode(elements.remoteOffer, "Invite code").catch(showError)); elements.pasteAnswer.addEventListener("click", () => pasteCode(elements.remoteAnswer, "Response code").catch(showError)); elements.toggleMic.addEventListener("click", () => toggleMicrophone().catch(showError)); elements.toggleCamera.addEventListener("click", () => toggleCamera().catch(showError)); elements.sideBySide.addEventListener("click", toggleSideBySide); elements.switchScreens.addEventListener("click", switchScreens); elements.toggleFullscreen.addEventListener("click", () => toggleFullscreen().catch(showError)); elements.toggleChat.addEventListener("click", () => setChatVisible(elements.chatPanel.hidden)); elements.closeChat.addEventListener("click", () => setChatVisible(false)); elements.chatForm.addEventListener("submit", sendChatMessage); elements.showVerification.addEventListener("click", () => setVerificationVisible(elements.verificationCard.hidden)); elements.hideVerification.addEventListener("click", () => setVerificationVisible(false)); elements.localVideoCard.addEventListener("pointerdown", beginTileDrag); elements.remoteVideoCard.addEventListener("pointerdown", beginTileDrag); elements.disconnect.addEventListener("click", disconnect); elements.remoteOffer.addEventListener("input", saveSession); elements.remoteAnswer.addEventListener("input", saveSession); document.addEventListener("fullscreenchange", syncFullscreenControl); window.addEventListener("popstate", blockBrowserBackNavigation); window.addEventListener("keydown", blockBackShortcuts); window.addEventListener("pagehide", releaseLiveResources); syncChatControls(); syncFullscreenControl(); lockBrowserBackNavigation(); restoreSetup();
