// STUN improves direct cross-city connectivity; no TURN relay is configured.
const rtcConfig = { iceServers: [{ urls: "stun:stun.l.google.com:19302" }] };
const storageKey = "our-private-life-session";
let peerConnection, localStream, offerCode = "", answerCode = "";
const $ = (id) => document.getElementById(id);
const elements = {
  setupPage: $("setupPage"), callPage: $("callPage"), localVideo: $("localVideo"), remoteVideo: $("remoteVideo"), start: $("startCameraButton"), createOffer: $("createOfferButton"), createAnswer: $("createAnswerButton"), acceptAnswer: $("acceptAnswerButton"), enterCallAfterAnswer: $("enterCallAfterAnswerButton"), toggleMic: $("toggleMicButton"), toggleCamera: $("toggleCameraButton"), sideBySide: $("sideBySideButton"), switchScreens: $("switchScreensButton"), disconnect: $("disconnectButton"), remoteOffer: $("remoteOffer"), remoteAnswer: $("remoteAnswer"), copyOffer: $("copyOfferButton"), copyAnswer: $("copyAnswerButton"), receiverCard: $("receiverCard"), answerReady: $("answerReady"), callerAnswerCard: $("callerAnswerCard"), statusText: $("statusText"), statusDot: $("statusDot"), callStatusText: $("callStatusText"), callStatusDot: $("callStatusDot"), videos: $("videos"), localVideoCard: $("localVideoCard"), remoteVideoCard: $("remoteVideoCard")
};
function saveSession() { sessionStorage.setItem(storageKey, JSON.stringify({ offerCode, answerCode, remoteOffer: elements.remoteOffer.value, remoteAnswer: elements.remoteAnswer.value, sideBySide: elements.videos.classList.contains("side-by-side"), screensSwapped: elements.videos.classList.contains("screens-swapped") })); }
function clearSession() { sessionStorage.removeItem(storageKey); }
function setStatus(message, state = "idle") { [elements.statusText, elements.callStatusText].forEach(node => { node.textContent = message; }); [elements.statusDot, elements.callStatusDot].forEach(node => { node.className = `dot ${state}`; }); }
function showError(error) { console.error(error); setStatus(`Error: ${error.message || error}`, "error"); }
function setBusy(button, busy, label) { button.disabled = busy; if (label) button.textContent = label; }
function encodeCode(description) { const bytes = new TextEncoder().encode(JSON.stringify(description)); return btoa(String.fromCharCode(...bytes)); }
function decodeCode(code, expectedType) { try { const bytes = Uint8Array.from(atob(code.trim().replace(/\s/g, "")), c => c.charCodeAt(0)); const value = JSON.parse(new TextDecoder().decode(bytes)); if (value?.type === expectedType && value?.sdp) return value; } catch {} throw new Error(`Paste a valid ${expectedType === "offer" ? "invite" : "response"} code.`); }
function syncMediaControls() { const audio = localStream?.getAudioTracks()[0], video = localStream?.getVideoTracks()[0]; elements.toggleMic.disabled = !audio; elements.toggleCamera.disabled = !video; if (audio) { const muted = !audio.enabled; elements.toggleMic.setAttribute("aria-label", muted ? "Unmute microphone" : "Mute microphone"); elements.toggleMic.title = muted ? "Unmute microphone" : "Mute microphone"; elements.toggleMic.setAttribute("aria-pressed", String(muted)); } if (video) { const off = !video.enabled; elements.toggleCamera.setAttribute("aria-label", off ? "Turn camera on" : "Turn camera off"); elements.toggleCamera.title = off ? "Turn camera on" : "Turn camera off"; elements.toggleCamera.setAttribute("aria-pressed", String(off)); elements.localVideoCard.classList.toggle("camera-disabled", off); } }
function toggleTrack(kind) { const track = kind === "audio" ? localStream?.getAudioTracks()[0] : localStream?.getVideoTracks()[0]; if (!track) return showError(new Error("Enable camera and microphone first.")); track.enabled = !track.enabled; syncMediaControls(); setStatus(track.enabled ? `${kind === "audio" ? "Microphone" : "Camera"} turned on` : `${kind === "audio" ? "Microphone muted" : "Camera turned off"}`, "ready"); }
async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) throw new Error("Camera/microphone access requires HTTPS or localhost."); if (!localStream) { localStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); elements.localVideo.srcObject = localStream; } elements.start.textContent = "Camera & microphone enabled"; elements.start.disabled = true; elements.createOffer.disabled = false; syncMediaControls(); setStatus("Camera and microphone ready", "ready"); }
function makePeerConnection() { if (peerConnection) return peerConnection; if (!localStream) throw new Error("Enable camera and microphone first."); peerConnection = new RTCPeerConnection(rtcConfig); localStream.getTracks().forEach(track => peerConnection.addTrack(track, localStream)); peerConnection.ontrack = ({ streams }) => { elements.remoteVideo.srcObject = streams[0]; }; peerConnection.onconnectionstatechange = () => { const state = peerConnection.connectionState; setStatus(`Connection: ${state}`, state === "connected" ? "connected" : state === "failed" ? "error" : "working"); }; elements.disconnect.disabled = false; return peerConnection; }
function waitForIceGatheringComplete(pc) { if (pc.iceGatheringState === "complete") return Promise.resolve(); return new Promise(resolve => { const done = () => { if (pc.iceGatheringState === "complete") { pc.removeEventListener("icegatheringstatechange", done); resolve(); } }; pc.addEventListener("icegatheringstatechange", done); }); }
async function copyCode(code, label) { if (!code) throw new Error("Create the code first."); await navigator.clipboard.writeText(code); setStatus(`${label} copied — send it to your friend`, "ready"); }
function enterCall() { elements.setupPage.hidden = true; elements.callPage.hidden = false; document.title = "Our Private Life — Call"; saveSession(); }
async function createOffer() { try { const pc = makePeerConnection(); setBusy(elements.createOffer, true, "Creating invite…"); await pc.setLocalDescription(await pc.createOffer()); await waitForIceGatheringComplete(pc); offerCode = encodeCode(pc.localDescription); elements.copyOffer.disabled = false; elements.receiverCard.hidden = true; elements.callerAnswerCard.hidden = false; elements.createOffer.textContent = "Invite created"; saveSession(); setStatus("Invite ready — copy and send it", "ready"); } catch (error) { showError(error); setBusy(elements.createOffer, false, "Create invite"); } }
async function createAnswer() { try { setBusy(elements.createAnswer, true, "Creating response…"); if (!localStream) await startCamera(); const pc = makePeerConnection(); await pc.setRemoteDescription(decodeCode(elements.remoteOffer.value, "offer")); await pc.setLocalDescription(await pc.createAnswer()); await waitForIceGatheringComplete(pc); answerCode = encodeCode(pc.localDescription); elements.remoteOffer.hidden = true; elements.createAnswer.hidden = true; elements.answerReady.hidden = false; saveSession(); setStatus("Response ready — copy and send it", "ready"); } catch (error) { showError(error); setBusy(elements.createAnswer, false, "Accept invite & create response"); } }
async function acceptAnswer() { try { if (!peerConnection || !offerCode || peerConnection.signalingState !== "have-local-offer") throw new Error("Invite is no longer active. Create a new invite in this same browser tab; do not reload it."); await peerConnection.setRemoteDescription(decodeCode(elements.remoteAnswer.value, "answer")); saveSession(); setStatus("Response accepted — connecting…", "working"); enterCall(); } catch (error) { showError(error); } }
function toggleSideBySide() { const active = elements.videos.classList.toggle("side-by-side"); elements.sideBySide.setAttribute("aria-pressed", String(active)); elements.sideBySide.setAttribute("aria-label", active ? "Switch to picture-in-picture view" : "Switch to side-by-side view"); elements.sideBySide.title = active ? "Picture-in-picture view" : "Side-by-side view"; saveSession(); }
function resetTilePosition(card) { card.style.left = ""; card.style.top = ""; card.style.right = ""; card.style.bottom = ""; }
function switchScreens() { resetTilePosition(elements.localVideoCard); resetTilePosition(elements.remoteVideoCard); elements.videos.classList.toggle("screens-swapped"); saveSession(); }
function floatingCard() { return elements.videos.classList.contains("screens-swapped") ? elements.remoteVideoCard : elements.localVideoCard; }
let tileInteraction;
function beginTileDrag(event) { const card = floatingCard(); if (elements.videos.classList.contains("side-by-side") || event.currentTarget !== card || event.target.closest("button")) return; event.preventDefault(); const stage = elements.videos.getBoundingClientRect(), tile = card.getBoundingClientRect(); card.style.left = `${tile.left - stage.left}px`; card.style.top = `${tile.top - stage.top}px`; card.style.right = "auto"; card.style.bottom = "auto"; tileInteraction = { card, stage, offsetX: event.clientX - tile.left, offsetY: event.clientY - tile.top }; document.addEventListener("pointermove", moveTile); document.addEventListener("pointerup", endTileDrag); document.addEventListener("pointercancel", endTileDrag); }
function moveTile(event) { if (!tileInteraction) return; const { card, stage, offsetX, offsetY } = tileInteraction; const left = Math.min(Math.max(event.clientX - stage.left - offsetX, 0), stage.width - card.offsetWidth); const top = Math.min(Math.max(event.clientY - stage.top - offsetY, 0), stage.height - card.offsetHeight); card.style.left = `${left}px`; card.style.top = `${top}px`; }
function endTileDrag() { tileInteraction = undefined; document.removeEventListener("pointermove", moveTile); document.removeEventListener("pointerup", endTileDrag); document.removeEventListener("pointercancel", endTileDrag); }
function releaseLiveResources() { if (peerConnection) peerConnection.close(); if (localStream) localStream.getTracks().forEach(track => track.stop()); }
function disconnect() { releaseLiveResources(); peerConnection = undefined; localStream = undefined; offerCode = answerCode = ""; clearSession(); elements.localVideo.srcObject = null; elements.remoteVideo.srcObject = null; elements.localVideoCard.classList.remove("camera-disabled"); elements.videos.classList.remove("side-by-side", "screens-swapped"); resetTilePosition(elements.localVideoCard); resetTilePosition(elements.remoteVideoCard); elements.sideBySide.setAttribute("aria-pressed", "false"); elements.setupPage.hidden = false; elements.callPage.hidden = true; document.title = "Our Private Life — Direct Call"; elements.start.disabled = false; elements.start.textContent = "Enable camera & microphone"; elements.createOffer.disabled = true; elements.createOffer.textContent = "Create invite"; elements.copyOffer.disabled = true; elements.toggleMic.disabled = true; elements.toggleCamera.disabled = true; elements.disconnect.disabled = true; elements.receiverCard.hidden = false; elements.remoteOffer.hidden = false; elements.remoteOffer.value = ""; elements.createAnswer.hidden = false; elements.createAnswer.disabled = false; elements.createAnswer.textContent = "Accept invite & create response"; elements.answerReady.hidden = true; elements.callerAnswerCard.hidden = true; elements.remoteAnswer.value = ""; setStatus("Disconnected", "idle"); }
function restoreSetup() { try { const saved = JSON.parse(sessionStorage.getItem(storageKey) || "null"); if (!saved) return; offerCode = saved.offerCode || ""; answerCode = saved.answerCode || ""; elements.remoteOffer.value = saved.remoteOffer || ""; elements.remoteAnswer.value = saved.remoteAnswer || ""; if (saved.screensSwapped) elements.videos.classList.add("screens-swapped"); if (saved.sideBySide) toggleSideBySide(); if (offerCode) { elements.copyOffer.disabled = false; elements.receiverCard.hidden = true; elements.callerAnswerCard.hidden = false; elements.createOffer.textContent = "Invite created"; } } catch { clearSession(); } }
elements.start.addEventListener("click", () => startCamera().catch(showError)); elements.createOffer.addEventListener("click", createOffer); elements.createAnswer.addEventListener("click", createAnswer); elements.acceptAnswer.addEventListener("click", acceptAnswer); elements.enterCallAfterAnswer.addEventListener("click", enterCall); elements.copyOffer.addEventListener("click", () => copyCode(offerCode, "Invite code").catch(showError)); elements.copyAnswer.addEventListener("click", () => copyCode(answerCode, "Response code").catch(showError)); elements.toggleMic.addEventListener("click", () => toggleTrack("audio")); elements.toggleCamera.addEventListener("click", () => toggleTrack("video")); elements.sideBySide.addEventListener("click", toggleSideBySide); elements.switchScreens.addEventListener("click", switchScreens); elements.localVideoCard.addEventListener("pointerdown", beginTileDrag); elements.remoteVideoCard.addEventListener("pointerdown", beginTileDrag); elements.disconnect.addEventListener("click", disconnect); elements.remoteOffer.addEventListener("input", saveSession); elements.remoteAnswer.addEventListener("input", saveSession); window.addEventListener("pagehide", releaseLiveResources); restoreSetup();
